name: Movecraft-ShipRules
main: net.countercraft.movecraft.rules.MovecraftShipRules
version: ${project.version}
api-version: 1.16
author: a4bde, TylerS1066
depend: [Movecraft]
permissions:
  movecraft.rules.bypass:
    description: Allows a player to bypass ship rules and pilot an illegal ship.
    default: false
